spring.application.name=multiuserverse_backend

# Use Render's database environment variables, fallback to local if not set
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/multiuserverse}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:sesame}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
..........

# JWT Secret Key (Replace with a long, random Base64 string)
jwt.secret=91PulY4teOqoIkEuUWOinSr8XpJbu1PlHvInuBtU6zk=
